version: '3.9'

services:
  mc-api-nginx:
    container_name: mc-api-nginx
    image: nginx:stable
    depends_on:
      - mc-phpfpm
    networks:
      - medcenter24-network
      - traefik-public
    volumes:
      - ..:/var/www/html:cached
      - ./nginx/api.nginx.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mc-api.rule=Host(`mc-api.docker.localhost`)"
      - "traefik.http.routers.mc-api.entrypoints=http"
      - "traefik.http.routers.mc-api-secure.entrypoints=https"
      - "traefik.http.routers.mc-api-secure.rule=Host(`mc-api.docker.localhost`)"
      - "traefik.http.routers.mc-api-secure.tls=true"

  mc-backoffice-nginx:
    container_name: mc-backoffice-nginx
    image: nginx:stable
    environment:
      - PHP_IDE_CONFIG="serverName=PHPStorm"
    depends_on:
      - mc-phpfpm
    networks:
      - medcenter24-network
      - traefik-public
    volumes:
      - ..:/var/www/html:cached
      - ./nginx/backoffice.nginx.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mc-backoffice.rule=Host(`mc-backoffice.docker.localhost`)"
      - "traefik.http.routers.mc-backoffice.entrypoints=http"
      - "traefik.http.routers.mc-backoffice-secure.entrypoints=https"
      - "traefik.http.routers.mc-backoffice-secure.rule=Host(`mc-backoffice.docker.localhost`)"
      - "traefik.http.routers.mc-backoffice-secure.tls=true"

#  mc-doctor-nginx:
#    container_name: mc-doctor-nginx
#    image: nginx:stable
#    depends_on:
#      - mc-phpfpm
#    networks:
#      - medcenter24-network
#      - traefik-public
#    volumes:
#      - ..:/var/www/html:cached
#      - ./nginx/doctor.nginx.conf:/etc/nginx/conf.d/default.conf:cached
#    working_dir: /etc/nginx/conf.d
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.mc-doctor.rule=Host(`doctor.mc.docker.localhost`)"
#      - "traefik.http.routers.mc-doctor.entrypoints=http"
#      - "traefik.http.routers.mc-doctor-secure.entrypoints=https"
#      - "traefik.http.routers.mc-doctor-secure.rule=Host(`doctor.mc.docker.localhost`)"
#      - "traefik.http.routers.mc-doctor-secure.tls=true"

  mc-director-dist-nginx:
    container_name: mc-director-dist-nginx
    image: nginx:stable
    depends_on:
      - mc-phpfpm
    networks:
      - medcenter24-network
      - traefik-public
    volumes:
      - ..:/var/www/html:cached
      - ./nginx/director.nginx.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mc-director-dist.rule=Host(`director-dist-mc.docker.localhost`)"
      - "traefik.http.routers.mc-director-dist.entrypoints=http"
      - "traefik.http.routers.mc-director-dist-secure.entrypoints=https"
      - "traefik.http.routers.mc-director-dist-secure.rule=Host(`director-dist-mc.docker.localhost`)"
      - "traefik.http.routers.mc-director-dist-secure.tls=true"

  mc-phpfpm:
    container_name: mc-phpfpm
    build:
      context: ./phpfpm
    environment:
      - APP_CONFIG_PATH=/var/www/html/appSettings/config/generis.conf.php
      - CORS_ALLOW_ORIGIN_DIRECTOR_DEV=https://director-dist-mc.docker.localhost
      - CORS_ALLOW_ORIGIN_DOCTOR_DEV=https://doctor-dist-mc.docker.localhost
    networks:
      - medcenter24-network
    volumes:
      - ..:/var/www/html:cached
    working_dir: /var/www/html

  mc-build:
    container_name: mc-build
    build:
      context: ./build
    networks:
      - medcenter24-network
    volumes:
      - $PWD/../:/var/www/html:cached
    working_dir: /var/www/html

  mc-postgres:
    image: postgres:13.3
    container_name: mc-postgres
    networks:
      - medcenter24-network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=mc
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mc-pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mc-director-watch:
    container_name: mc-director-watch
    build:
      context: ./director-dev
    command: bash -c "yarn && yarn start --public-host http://mc-director-watch.docker.localhost --host 0.0.0.0 --disable-host-check"
    networks:
      - medcenter24-network
    volumes:
      - ..:/var/www/html:cached
    working_dir: /var/www/html/guiDirector

  mc-director-watch-nginx:
    container_name: mc-director-watch-nginx
    image: nginx:stable
    depends_on:
      - mc-director-watch
    networks:
      - medcenter24-network
      - traefik-public
    volumes:
      - ..:/var/www/html:cached
      - ./nginx/mc-director-watch.nginx.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mc-director-watch.rule=Host(`mc-director-watch.docker.localhost`)"
      - "traefik.http.routers.mc-director-watch.entrypoints=http"
      - "traefik.http.routers.mc-director-watch-secure.entrypoints=https"
      - "traefik.http.routers.mc-director-watch-secure.rule=Host(`mc-director-watch.docker.localhost`)"
      - "traefik.http.routers.mc-director-watch-secure.tls=true"

  mc-doctor-watch:
    container_name: mc-doctor-watch
    build:
      context: ./doctor-dev
    command: bash -c "yarn && yarn start --public-host http://mc-doctor-watch.docker.localhost --host 0.0.0.0 --disable-host-check"
    networks:
      - medcenter24-network
    volumes:
      - ..:/var/www/html:cached
    working_dir: /var/www/html/guiDoctor

  mc-doctor-watch-nginx:
    container_name: mc-doctor-watch-nginx
    image: nginx:stable
    depends_on:
      - mc-doctor-watch
    networks:
      - medcenter24-network
      - traefik-public
    volumes:
      - ..:/var/www/html:cached
      - ./nginx/doctor-watch.nginx.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mc-doctor-watch.rule=Host(`mc-doctor-watch.docker.localhost`)"
      - "traefik.http.routers.mc-doctor-watch.entrypoints=http"
      - "traefik.http.routers.mc-doctor-watch-secure.entrypoints=https"
      - "traefik.http.routers.mc-doctor-watch-secure.rule=Host(`mc-doctor-watch.docker.localhost`)"
      - "traefik.http.routers.mc-doctor-watch-secure.tls=true"

# todo run mails through dev mailhog env?
#  mail:
#    image: mailhog/mailhog
#    container_name: "mail"
#    logging:
#      driver: 'none'  # disable saving logs
#    expose:
#      - 1025 # smtp server
#      - 8025 # web ui
#    networks:
#      main:
#        aliases:
#          - mail

volumes:
  mc-pg-data:

networks:
  medcenter24-network:
    driver: bridge
  traefik-public:
    external: true
