#!/usr/bin/groovy

pipeline {
    agent { label 'mc-deploy' }

    stages {
        stage('Build') {
            steps {
                buildApp()
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
                echo 'Php unit testing...'
                echo 'FE guiDirector testing...'
                echo 'FE guiDoctor testing'
            }
        }

        stage('Bundles') {
            steps {
                echo 'mcCore bundling...'
                echo 'guiDirector bundling...'
                echo 'guiDoctor bundling...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
                echo 'Deploying mcCore...'
                echo 'Deploying guiDirector...'
                echo 'Deploying guiDirector...'
            }
        }
    }
}

def buildApp() {
    echo 'composer install...'
    echo 'yarn in McCore...'
    echo 'yarn in guiDirector...'
    echo 'yarn in guiDoctor...'
}
